[package]
name = "main-ui"
version = "0.3.15"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Rust Sdk Dependencies
by-components.workspace = true
dioxus-translate.workspace = true
dioxus-aws.workspace = true
by-types.workspace = true
rest-api.workspace = true
by-macros.workspace = true

# This Repo Dependencies
models.workspace = true

# Dioxus Dependencies
dioxus = { workspace = true, features = ["default", "fullstack", "router"] }

serde = { version = "1.0.197", features = ["derive"] }
chrono = "0.4"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
dioxus-logger = "0.5.1"
regex = "1.3.9"
sha3 = "0.10.8"
wasm-bindgen = { version = "0.2.100" }
wasm-bindgen-futures = { version = "0.4.49" }
web-sys = { version = "0.3.74" }
getrandom = { version = "0.2", features = ["js"] }
num-format = "0.4.4"
indexmap = "2.7.1"
btracing.workspace = true
tracing = "0.1.41"

[features]
default = []
server = ["dioxus-aws/server"]
lambda = ["dioxus-aws/lambda", "server"]
web = [
  "dioxus-aws/web",
  "dioxus-translate/web",
  "models/web",
]
