name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          WAIT_TIMEOUT: 5000
          VISIBLE_TIMEOUT: 10000
          URL_TIMEOUT: 15000
          GOOGLE_PASS: "123456789"
          GOOGLE_EMAIL: "testemail@gmail.com"
        run: |
          echo "Running tests with timeouts:"
          echo "WAIT_TIMEOUT=$WAIT_TIMEOUT"
          echo "VISIBLE_TIMEOUT=$VISIBLE_TIMEOUT"
          echo "URL_TIMEOUT=$URL_TIMEOUT"
          echo "GOOGLE_EMAIL=$GOOGLE_EMAIL"
          echo "GOOGLE_PASS=$GOOGLE_PASS"
          npx playwright test tests/users
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: screenshots
          path: screenshots/
          retention-days: 30
